import * as React from 'react';

export const DarkModeIcon = () => <span style={{fontSize:'1.5rem'}}>🌙</span>;
export const LightModeIcon = () => <span style={{fontSize:'1.5rem'}}>☀️</span>;
export const MenuBookIcon = () => <span style={{fontSize:'1.5rem'}}>📖</span>;
export const SelfImprovementIcon = () => <span style={{fontSize:'1.5rem'}}>🧘</span>;
export const MusicNoteIcon = () => <span style={{fontSize:'1.5rem'}}>🎵</span>;
export const RestaurantIcon = () => <span style={{fontSize:'1.5rem'}}>🍽️</span>;
export const LibraryBooksIcon = () => <span style={{fontSize:'1.5rem'}}>📚</span>;
export const TheaterComedyIcon = () => <span style={{fontSize:'1.5rem'}}>🎭</span>;
export const HomeIcon = () => <span style={{fontSize:'1.5rem'}}>🏠</span>;
export const LocalLibraryIcon = () => <span style={{fontSize:'1.5rem'}}>🏛️</span>;
export const LocalDiningIcon = () => <span style={{fontSize:'1.5rem'}}>🍴</span>;
export const SpaIcon = () => <span style={{fontSize:'1.5rem'}}>💆</span>;
export const AccessTimeIcon = () => <span style={{fontSize:'1.5rem'}}>⏰</span>;
export const InstagramIcon = () => <span style={{fontSize:'1.5rem'}}>📸</span>;
export const YouTubeIcon = () => <span style={{fontSize:'1.5rem'}}>📺</span>;
export const PhoneIcon = () => <span style={{fontSize:'1.5rem'}}>📱</span>;
export const PlaceIcon = () => <span style={{fontSize:'1.5rem'}}>📍</span>;
export const GroupIcon = () => <span style={{fontSize:'1.5rem'}}>👥</span>;
export const VolunteerActivismIcon = () => <span style={{fontSize:'1.5rem'}}>🤝</span>;
export const GavelIcon = () => <span style={{fontSize:'1.5rem'}}>⚖️</span>;
export const MilitaryTechIcon = () => <span style={{fontSize:'1.5rem'}}>🎖️</span>;
export const HikingIcon = () => <span style={{fontSize:'1.5rem'}}>🥾</span>;
export const FavoriteBorderIcon = () => <span style={{fontSize:'1.5rem'}}>❤️</span>;
